### ISSUE TITLE
Created Project Not Visible Across Multiple Browsers

### ISSUE THREAD

**Issue by itailiors** [block-core/angor#103]
When a user is connected on two different browsers and creates a project in one of them, the project is not visible in the other browser. 
(Because of the way the scan in founder works that it only scans once)

Steps to Reproduce:

Be on 'x' wallet on Browser A.
Be on 'x' wallet on Browser B.
Create a new Angor project on Browser A.

 p.s If it is the first project created by the user, it is possible that it will work as expected and be visible in both browsers.

**Comment by dangershony** [comment]
Was this issues fixed in this commit? https://github.com/block-core/angor/pull/101
@DavidGershony

**Comment by itailiors** [comment]
@dangershony @DavidGershony 

I think we can close this issue if when we decide on the following:

For example, if someone has two active instances of Angor and creates a project on instance A, should they see it on instance B? 
We can address this in two ways:
1. Add logic to scan founder projects that deletes the current data and derives from the start.
2. Require the user to wipe the data and recover the wallet.

I believe the first approach is more correct. If you agree, I can implement it.

**Comment by dangershony** [comment]
I believe after Davids recent changes this is not the case anymore

**Comment by itailiors** [comment]
> I believe after Davids recent changes this is not the case anymore

david's change was so the first load works, but we fetch only once now,
for example if you go now to the founder page you can see that the scan button isn't there because we already fetched.

and this problem we can solve with 1/2
