### ISSUE TITLE
Add the ability to redirect to a nostr client

### ISSUE THREAD

**Issue by dangershony** [block-core/angor#112]
We would like to let the user get redirected to a Nostr client where they can see updates about the project (the founder key will be the npub to reference to)
For that we need to add in settings specifying a Nostr client and maybe some way to format the url redirect for each client

**Comment by itailiors** [comment]
with this, we can also add a "share" button to our projects.

**Comment by dangershony** [comment]
This will actually happen in hub come to think about it

**Comment by itailiors** [comment]
now that i'm thinking on it again,
is angor-hub fulfilling this need @dangershony @miladsoft

**Comment by itailiors** [comment]
didn't notice this comment lol, so should we close this issue and move it to backboard task for hub?

> This will actually happen in hub come to think about it

**Comment by dangershony** [comment]
yes I will close it
