### ISSUE TITLE
 Unable to Create a Different Project After Completing the First Step of Project Creation and Nostr Profile Setup

### ISSUE THREAD

**Issue by itailiors** [block-core/angor#138]
When a user creates a project and completes the first step, including the creation of a Nostr profile for that project, they encounter an issue when trying to create a different project. Specifically, the process only allows the user to continue with the current project and change its details after obtaining a Nostr private key. This behavior can be misleading and difficult for users to understand, as they might expect to start a new project from scratch rather than modifying the existing one.

Steps to Reproduce:

1. Create a new project.
2. Complete the first step, including the creation of a Nostr profile for the project.
3. Attempt to create a different project.

Expected Behavior:
TBD.

Actual Behavior:
The user is only allowed to proceed with the existing project, and the option to create a different project from scratch is not available. This forces the user to change details in the current project, which may be confusing and misleading.

**Comment by dangershony** [comment]
One issues here is that the new project overrides the old one in the search page

![image](https://github.com/user-attachments/assets/f7c50c3f-c694-4b3f-818e-92e1bde53d50)

**Comment by dangershony** [comment]
Also we need to limit the penalty locktime (CSV) to not more then 388 days 
https://en.bitcoin.it/wiki/Timelock

**Comment by dangershony** [comment]
@DavidGershony this is an important issue because it makes the penalty not spendable so we must add this check in to the low level interface

**Comment by itailiors** [comment]
fixed in #175 , 
although we can maybe discuss on making a wipe storage for founder.
