### ISSUE TITLE
Mempool - improve stats endpoint

### ISSUE THREAD

**Issue by nostrdev-com** [block-core/angor#145]
The `/api/query/Angor/projects/{projectId}/stats` endpoint should also provide the following data: `amountSpentSoFarByFounder`, `amountInPenalties`, `countInPenalties`.
There is a MongoDB query to provide this data that can be useful.

**Comment by nostrdev-com** [comment]
@dangershony or @DavidGershony, it would be great if you could provide a link to the MongoDB query.

**Comment by nostrdev-com** [comment]
> @dangershony or @DavidGershony, it would be great if you could provide a link to the MongoDB query.

https://github.com/block-core/blockcore-indexer/blob/master/src/Blockcore.Indexer.Angor/Storage/Mongo/AngorMongoData.cs#L86

**Comment by dangershony** [comment]
Did this help?

**Comment by nostrdev-com** [comment]
This task has now been completed and merged into the master branch.
