### ISSUE TITLE
Mempool - missing projects in the project endpoint

### ISSUE THREAD

**Issue by DavidGershony** [block-core/angor#158]
Calling to https://tbtc.indexer.angor.io/api/query/Angor/projects/angor1q83m8ecz3g86nyyq9u8n9knajpdd87p84d9rp9w
I am getting the result -
{
  "founderKey": "038eb4fbfd8909885103064a9d6347ec0a210e2fac37fa659f43d71031ce7494b7",
  "nostrPubKey": "b91ec0fab65bdc4283a4bbc41e3b2548c29d2ba7ca5bd7ef980c3b0499fea19d",
  "projectIdentifier": "angor1q83m8ecz3g86nyyq9u8n9knajpdd87p84d9rp9w",
  "createdOnBlock": 19410,
  "trxId": "a9ebdee99833e76f85a80b96bd556803ca528fc383c6d754e9393e2cfa61dd27",
  "totalInvestmentsCount": 0
}
but when I call the mempool api for the same endpoint I get not found (404).

**Comment by nostrdev-com** [comment]
The error was due to 1) some values exceeding the length as defined in the database schema 2) Angor indexing not finishing its job. Both issues have now been fixed.
