### ISSUE TITLE
Wallet Doesn't Show Fiat Value

### ISSUE THREAD

**Issue by itailiors** [block-core/angor#161]
The interface is currently not displaying the fiat value.

To Do:

- Debug why BtcBalanceInFiat is null.

Testing Information:

- The API has been tested and is working correctly.

**Comment by dangershony** [comment]
Just o be sure are you on mainnet?

**Comment by itailiors** [comment]
> Just o be sure are you on mainnet?

Nice catch! I've forgot that...
Closing the issue
