### ISSUE TITLE
Edge Case - Trying to create more than 15 projects

### ISSUE THREAD

**Issue by itailiors** [block-core/angor#166]
whenever you try to create more than 15 projects you get this:

![image](https://github.com/user-attachments/assets/ddfd1ff0-4de0-4708-afa5-40e9b04c0b58)

This appears to be a rare edge case, as it's unlikely anyone will create more than 15 projects. However, it could be addressed with a few lines of code.

Proposed fix: Add a check before creating a project (if not already implemented) and disable the create page when the project count exceeds 15

**Comment by dangershony** [comment]
Sounds like the right solution, I think we just run out of keys that's why the error, it should be a better error though.
Generally I don't expect ever to make more then one project per wallet but who knows.

**Comment by itailiors** [comment]
fixed with #203
