### ISSUE TITLE
Should the app auto update when new versions are available?

### ISSUE THREAD

**Issue by dangershony** [block-core/angor#53]
I believe this should not be automatically for security concerns.
If a new version is available the app should notify the user and let them trigger the update.

**Comment by dangershony** [comment]
Ok so we need to do it with a user prompt

**Comment by dangershony** [comment]
I think this issue should be solved now?

**Comment by miladsoft** [comment]
yes. solved

**Comment by dangershony** [comment]
how will it work now? can you link to the code that handles the update?

**Comment by miladsoft** [comment]
https://github.com/block-core/angor/blob/e62b40303b48042460c14cb7eb8433d044396f83/src/Angor/Client/Shared/MainLayout.razor#L89

**Comment by dangershony** [comment]
ah wrong issue, this is about autoupdate when a new version is released

**Comment by miladsoft** [comment]
hahah . I will fix this too.

**Comment by miladsoft** [comment]
![image](https://github.com/user-attachments/assets/5dd4b80b-6c53-4ee0-8e9a-2707f8cdb637)

**Comment by itailiors** [comment]
> ![image](https://private-user-images.githubusercontent.com/6504337/380372868-5dd4b80b-6c53-4ee0-8e9a-2707f8cdb637.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDU3MzcsIm5iZiI6MTczMzQwNTQzNywicGF0aCI6Ii82NTA0MzM3LzM4MDM3Mjg2OC01ZGQ0YjgwYi02YzUzLTRlZTAtOGU5YS0yNzA3ZjhjZGI2MzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDVUMTMzMDM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTY3NjFiYzIzYzYxZjM3NDA1ZTA2ZGM0MjExMzM4YmMwYzUyMGJiODc4OTM2YjBjYjRhN2FjNDQxOTA2M2JjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.YhVQZkYbMNd9irDeU8CMpxw1WdPe8017RkqkHpiydxk)

@miladsoft Do you think something like this instead would be good as cache busting:
chat-gpt gave me something like this for service-worker.js, 
and then we can add to the CI/CD the changes for cache_name. (i've another branch with something that is similar seems a bit off)
```

const CACHE_NAME = 'angor-cache-v2'; // Increment version for updates
const urlsToCache = [
    '/index.html',
    '/styles.css',
    '/script.js',
    `/service-worker.js?cachebust=${Date.now()}`, // Append query string to force browser fetch
];

self.addEventListener('install', (event) => {
    event.waitUntil(
        caches.open(CACHE_NAME).then((cache) => {
            return cache.addAll(urlsToCache);
        })
    );
});

self.addEventListener('activate', (event) => {
    // Delete old caches
    event.waitUntil(
        caches.keys().then((cacheNames) => {
            return Promise.all(
                cacheNames.map((cacheName) => {
                    if (cacheName !== CACHE_NAME) {
                        return caches.delete(cacheName);
                    }
                })
            );
        })
    );
});

self.addEventListener('fetch', (event) => {
    event.respondWith(
        caches.match(event.request).then((response) => {
            // Fetch from network if not in cache
            return (
                response ||
                fetch(event.request).then((networkResponse) => {
                    return caches.open(CACHE_NAME).then((cache) => {
                        cache.put(event.request, networkResponse.clone());
                        return networkResponse;
                    });
                })
            );
        })
    );
});
```

**Comment by dangershony** [comment]
@sondreb added already some code to stop catching, please check it now

**Comment by itailiors** [comment]
Splendid, closing this issue then.

> @sondreb added already some code to stop catching, please check it now
